/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.prog2.main;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Seanzilla
 */
public class Employees extends javax.swing.JFrame {

    /**
     * Creates new form Employees
     */
    //Create the column names
    String[] teacherColumnNames = {"ID", "Name", "Birthdate", "Address", "Gender", "Specialty", "Degree", "Workload", "Status", "Department ID", "Salary"};
    String[] staffColumnNames = {"ID", "Name", "Birthdate", "Address", "Gender", "Duty", "Workload", "Status", "Department ID", "Salary"};
    
    public Object[][] teacherData() {
        //Converts the array list into a array of Object
        Object[][] teacherData = new Object[MainFrame.teacherList.size()][11];

        for (int i = 0; i < MainFrame.teacherList.size(); i++) {
            Teacher teacher = MainFrame.teacherList.get(i);
            teacherData[i][0] = teacher.getID();
            teacherData[i][1] = teacher.getName();
            teacherData[i][2] = teacher.getBirthdate();
            teacherData[i][3] = teacher.getAddress();
            teacherData[i][4] = teacher.getGender();
            teacherData[i][5] = teacher.getSpecialty();
            teacherData[i][6] = teacher.getDegree();
            teacherData[i][7] = teacher.getWorkload();
            teacherData[i][8] = teacher.getStatus();
            teacherData[i][9] = teacher.getDepartmentID();
            teacherData[i][10] = teacher.computePayRoll();
        }
        return teacherData;
    }

    DefaultTableModel teacherTableModel = new DefaultTableModel(teacherData(), teacherColumnNames);

    public Object[][] staffData() {
        Object[][] staffData = new Object[MainFrame.staffList.size()][10];

        for (int i = 0; i < MainFrame.staffList.size(); i++) {
            Staff staff = MainFrame.staffList.get(i);
            staffData[i][0] = staff.getID();
            staffData[i][1] = staff.getName();
            staffData[i][2] = staff.getBirthdate();
            staffData[i][3] = staff.getAddress();
            staffData[i][4] = staff.getGender();
            staffData[i][5] = staff.getDuty();
            staffData[i][6] = staff.getWorkload();
            staffData[i][7] = staff.getStatus();
            staffData[i][8] = staff.getDepartmentID();
            staffData[i][9] = staff.computePayRoll();
        }
        return staffData;
    }

    DefaultTableModel staffTableModel = new DefaultTableModel(staffData(), staffColumnNames);
    DefaultTableModel deanTableModel = new DefaultTableModel(deanData(), teacherColumnNames);

    public Object[][] deanData() {
        Object[][] deanData = new Object[MainFrame.deanList.size()][11];

        for (int i = 0; i < MainFrame.deanList.size(); i++) {
            Teacher dean = MainFrame.deanList.get(i);
            deanData[i][0] = dean.getID();
            deanData[i][1] = dean.getName();
            deanData[i][2] = dean.getBirthdate();
            deanData[i][3] = dean.getAddress();
            deanData[i][4] = dean.getGender();
            deanData[i][5] = dean.getSpecialty();
            deanData[i][6] = dean.getDegree();
            deanData[i][7] = dean.getWorkload();
            deanData[i][8] = dean.getStatus();
            deanData[i][9] = dean.getDepartmentID();
            deanData[i][10] = dean.computePayRoll();
        }
        return deanData;
    }

    public Employees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        staffTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        deptSelector = new javax.swing.JComboBox<>();
        cancelBTN1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        teacherTable = new javax.swing.JTable();

        staffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Birthdate", "Address", "Gender", "Duty", "Workload", "Status", "Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(staffTable);
        if (staffTable.getColumnModel().getColumnCount() > 0) {
            staffTable.getColumnModel().getColumn(0).setHeaderValue("ID");
            staffTable.getColumnModel().getColumn(1).setHeaderValue("Name");
            staffTable.getColumnModel().getColumn(2).setHeaderValue("Birthdate");
            staffTable.getColumnModel().getColumn(3).setHeaderValue("Address");
            staffTable.getColumnModel().getColumn(4).setHeaderValue("Gender");
            staffTable.getColumnModel().getColumn(5).setHeaderValue("Specialty");
            staffTable.getColumnModel().getColumn(6).setHeaderValue("Workload");
            staffTable.getColumnModel().getColumn(7).setHeaderValue("Status");
            staffTable.getColumnModel().getColumn(8).setHeaderValue("Salary");
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Centaur", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("View Employees");

        deptSelector.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        deptSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Teachers", "All Staff", "All Deans"}));
        deptSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptSelectorActionPerformed(evt);
            }
        });

        cancelBTN1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        cancelBTN1.setText("Go Back");
        cancelBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTN1ActionPerformed(evt);
            }
        });

        teacherTable.setModel(teacherTableModel);
        jScrollPane3.setViewportView(teacherTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addGap(151, 151, 151))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(deptSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(cancelBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deptSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(cancelBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deptSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptSelectorActionPerformed
        // TODO add your handling code here:
        //Set's the table model whichever is selected
        if (deptSelector.getSelectedIndex() == 0) {
            teacherTable.setModel(teacherTableModel);

        }
        if (deptSelector.getSelectedIndex() == 1) {
            teacherTable.setModel(staffTableModel);
        }
        if (deptSelector.getSelectedIndex() == 2) {
            teacherTable.setModel(deanTableModel);
        }

    }//GEN-LAST:event_deptSelectorActionPerformed

    private void cancelBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTN1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelBTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBTN1;
    private javax.swing.JComboBox<String> deptSelector;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable staffTable;
    private javax.swing.JTable teacherTable;
    // End of variables declaration//GEN-END:variables
}
