/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.prog2.main;

import javax.swing.JOptionPane;

/**
 *
 * @author Seanzilla
 */
public class NewTeacher extends javax.swing.JFrame {

    /**
     * Creates new form NewTeacher
     */
    char gender;

    public NewTeacher() {
        initComponents();
    }

    //gives the next teacher/dean ID that hasn't been used
    public int nextId() {
        int nextId = 0;
        for (Teacher teacher : MainFrame.teacherList) {
            if (teacher.getID() > nextId) {
                nextId = teacher.getID();
            }
        }
        for (Teacher dean : MainFrame.deanList) {
            if (dean.getID() > nextId) {
                nextId = dean.getID();
            }
        }
        return nextId + 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cancelBTN = new javax.swing.JButton();
        submitBTN = new javax.swing.JButton();
        isDeanInput = new javax.swing.JCheckBox();
        nameInput = new javax.swing.JTextField();
        IDinput = new javax.swing.JTextField(Integer.toString(nextId()));
        bdayInput = new javax.swing.JTextField();
        addressInput = new javax.swing.JTextField();
        workloadInput = new javax.swing.JTextField();
        specialtyInput = new javax.swing.JTextField();
        genderBTNM = new javax.swing.JRadioButton();
        genderBTNF = new javax.swing.JRadioButton();
        degreeInput = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        deptInput = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Teacher ID: ");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Address:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Birthdate (yyyy-MM-dd):");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Gender:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Specialty:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Workload:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Degree:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Department:");

        cancelBTN.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        cancelBTN.setText("Cancel");
        cancelBTN.setMaximumSize(new java.awt.Dimension(73, 23));
        cancelBTN.setMinimumSize(new java.awt.Dimension(73, 23));
        cancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTNActionPerformed(evt);
            }
        });

        submitBTN.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        submitBTN.setText("Submit");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        isDeanInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        isDeanInput.setText("Is Dean");
        isDeanInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isDeanInputActionPerformed(evt);
            }
        });

        nameInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        IDinput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        bdayInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        addressInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        workloadInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        specialtyInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        genderBTNM.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        genderBTNM.setText("M");
        genderBTNM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderBTNMActionPerformed(evt);
            }
        });

        genderBTNF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        genderBTNF.setText("F");
        genderBTNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderBTNFActionPerformed(evt);
            }
        });

        degreeInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        degreeInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bachelor's", "Master's", "PhD"}));

        jLabel10.setFont(new java.awt.Font("Centaur", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Add Teacher");

        deptInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        deptInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Science", "Humanities", "Math"}));
        deptInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(59, 59, 59))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(specialtyInput)
                                        .addComponent(deptInput, 0, 146, Short.MAX_VALUE)
                                        .addComponent(workloadInput)
                                        .addComponent(isDeanInput, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(degreeInput, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(36, 36, 36))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(65, 65, 65)
                                    .addComponent(genderBTNM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(genderBTNF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bdayInput)
                                        .addComponent(addressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(59, 59, 59)
                                    .addComponent(IDinput, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(cancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(IDinput, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nameInput)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(bdayInput)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(addressInput)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderBTNM)
                    .addComponent(genderBTNF))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(specialtyInput, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degreeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workloadInput, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(deptInput)))
                .addGap(18, 18, 18)
                .addComponent(isDeanInput)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelBTNActionPerformed

    private void isDeanInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isDeanInputActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_isDeanInputActionPerformed

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        // TODO add your handling code here:
        try {
            if (!isDeanInput.isSelected()) {
                if (genderBTNM.isSelected()) {
                    gender = 'M';
                }
                if (genderBTNF.isSelected()) {
                    gender = 'F';
                }
                //Creates new teacher
                Teacher newTeacher = new Teacher(Integer.parseInt(IDinput.getText()), nameInput.getText(), bdayInput.getText(), addressInput.getText(), gender, specialtyInput.getText(), degreeInput.getSelectedItem().toString(), Double.parseDouble(workloadInput.getText()), (deptInput.getSelectedIndex() + 11));
                //Checks for matching ID
                for (Teacher teacher : MainFrame.teacherList) {
                    if (Integer.parseInt(IDinput.getText()) == teacher.getID()) {
                        JOptionPane.showMessageDialog(null, "Error: ID already exists");
                        return;
                    }
                }
                //Checks that workload isn't too high
                if (Double.parseDouble(workloadInput.getText()) > 40) {
                    JOptionPane.showMessageDialog(null, "Error: Workload can not be over 40 hours");
                    return;
                }
                //Adds to array list in MainFrame and writes to the file
                MainFrame.teacherList.add(newTeacher);
                MainFrame.writeFileTeacher("TeacherList.txt", newTeacher);
            }
            if (isDeanInput.isSelected()) {
                Dean newDean = new Dean(Integer.parseInt(IDinput.getText()), nameInput.getText(), bdayInput.getText(), addressInput.getText(), gender, specialtyInput.getText(), degreeInput.getSelectedItem().toString(), Double.parseDouble(workloadInput.getText()), (deptInput.getSelectedIndex() + 11));
                for (Department department : MainFrame.departmentList) {
                    if (department.getDepartmentID() == (deptInput.getSelectedIndex() + 11)) {
                        if (department.getDean() != null) {
                            JOptionPane.showMessageDialog(null, "Error: this department already has a dean");
                            return;
                        }
                    }
                }
                if (Double.parseDouble(workloadInput.getText()) > 40) {
                    JOptionPane.showMessageDialog(null, "Error: Workload can not be over 40 hours");
                    return;
                }
                MainFrame.deanList.add(newDean);
                MainFrame.writeFileDean("TeacherList.txt", newDean);
            }

            MainFrame.setLists();
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Incorrect data input");
        }
    }//GEN-LAST:event_submitBTNActionPerformed

    private void genderBTNMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderBTNMActionPerformed
        // TODO add your handling code here:
        gender = 'M';
    }//GEN-LAST:event_genderBTNMActionPerformed

    private void genderBTNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderBTNFActionPerformed
        // TODO add your handling code here:
        gender = 'F';
    }//GEN-LAST:event_genderBTNFActionPerformed

    private void deptInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptInputActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_deptInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDinput;
    private javax.swing.JTextField addressInput;
    private javax.swing.JTextField bdayInput;
    private javax.swing.JButton cancelBTN;
    private javax.swing.JComboBox<String> degreeInput;
    private javax.swing.JComboBox<String> deptInput;
    private javax.swing.JRadioButton genderBTNF;
    private javax.swing.JRadioButton genderBTNM;
    private javax.swing.JCheckBox isDeanInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField specialtyInput;
    private javax.swing.JButton submitBTN;
    private javax.swing.JTextField workloadInput;
    // End of variables declaration//GEN-END:variables
}
